baseURL = "http://banay.me/"
languageCode = "en-us"
title = "Moss' Blog"
theme = "angels-ladder"

[Params]
subtitle = "CS, Finance, Math"
facebook = "https://facebook.com/foobar"
twitter = "https://twitter.com/foobar"
github = "https://github.com/foobar"
showsRSS = true
analytics = "UA-XXXXXXXX-X"
shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
